import type { CmsPage, SiteConfig } from "@/types/content";

export const fallbackSite: SiteConfig = {
  siteName: "WeSoft",
  logo: { url: "/images/wesoft-logo.png", alternativeText: "WeSoft" },
  navigation: [
    { label: "Les solutions", href: "/#solutions" },
    { label: "Le processus d’acquisition", href: "/#processus" },
    { label: "Les ressources", href: "/articles" },
    { label: "Qui sommes-nous ?", href: "/#equipe" },
  ],
  headerButton: { label: "Contactez-nous", href: "/contact", style: "primary", linkType: "internal" },
  footerIntro: "Le partenaire de référence pour l’excellence opérationnelle et la croissance des éditeurs de logiciels verticaux.",
  footerColumns: [{ title: "Liens utiles", links: [{ label: "Nos solutions", href: "/#solutions" }, { label: "Notre processus d’acquisition", href: "/#processus" }, { label: "Qui sommes-nous ?", href: "/#equipe" }, { label: "Ressources", href: "/articles" }] }],
  socialLinks: [{ label: "Site WeSoft", href: "https://wesoft.group", linkType: "external" }, { label: "LinkedIn", href: "https://www.linkedin.com", linkType: "external" }],
  legalLinks: [{ label: "Mentions légales", href: "/mentions-legales" }, { label: "Politique de confidentialité", href: "/politique-de-confidentialite" }, { label: "RGPD", href: "/politique-de-confidentialite#vos-droits" }, { label: "Plan du site", href: "/plan-du-site" }],
  footerCtaTitle: "Un projet ?",
  copyright: "© 2024-2026 - WESOFT. Tous droits réservés.",
};

export const fallbackHome: CmsPage = {
  id: 1, title: "Accueil", slug: "accueil",
  blocks: [
    { id: 1, __component: "sections.hero", eyebrow: "GROUPE D’ÉDITION LOGICIELLE", title: "Nous accompagnons les éditeurs de logiciels verticaux dans leur croissance.", text: "L’expertise métier est le facteur essentiel de toute solution informatique. Nous apportons l’innovation technologique et l’accompagnement humain pour propulser votre solution.", image: { url: "/images/home-hero.png", alternativeText: "Interface logicielle professionnelle" }, showDecoration: true, floatingTitle: "Croissance Sectorielle", floatingText: "Performances optimisées", buttons: [{ label: "Découvrir nos solutions", href: "/#solutions", style: "primary" }, { label: "Qui sommes-nous ?", href: "/#equipe", style: "secondary" }], background: "lavender" },
    { id: 2, __component: "sections.feature-grid", anchorId: "solutions", title: "Nos 4 piliers stratégiques", text: "Une approche intégrée pour garantir le succès de votre transition numérique et métier.", background: "white", features: [{ title: "Expertise métier", text: "Compréhension profonde des enjeux quotidiens pour une réponse logicielle pertinente." }, { title: "Innovation technologique", text: "Une techno qui apporte un bénéfice métier réel. Pas de techno pour la techno." }, { title: "Accompagnement", text: "Renforcer la satisfaction client en s’appuyant sur l’énergie des équipes en place." }, { title: "Nouveau souffle", text: "Continuer à écrire l’histoire de votre solution dans le périmètre dynamique de WeSoft." }] },
    { id: 3, __component: "sections.process", anchorId: "processus", eyebrow: "TRANSMISSION", title: "Un processus d’acquisition serein et structuré", text: "Nous privilégions la continuité opérationnelle et le respect de votre ADN historique.", background: "sky", steps: [{ title: "Diagnostic stratégique", text: "Analyse approfondie de votre produit, de votre marché et de votre potentiel de scalabilité." }, { title: "Valorisation & offre", text: "Proposition financière transparente basée sur une vision long-terme et non spéculative." }, { title: "Intégration douce", text: "Mise en place de synergies groupe tout en préservant l’autonomie de vos équipes expertes." }, { title: "Accélération", text: "Déploiement du plan de croissance : R&D, marketing et expansion commerciale." }] },
    { id: 4, __component: "sections.software-showcase", title: "Une expertise sectorielle verticale", text: "Nos logiciels répondent aux besoins spécifiques de métiers exigeants, avec une connaissance fine de chaque secteur.", background: "white", items: [
      { name: "Agorinfo", sector: "Agriculture", description: "Digitalisation des exploitations, traçabilité et gestion des entreprises agricoles et agroalimentaires.", logo: { url: "/images/logo-agorinfo.png" }, image: { url: "/images/software-agorinfo.png" }, accentColor: "#7a2d9f", button: { label: "Visiter leur site", href: "https://www.agorinfo.fr", linkType: "external", openInNewTab: true }, capabilities: [{ text: "ERP pour les libres services agricoles" }, { text: "ERP pour les coopératives de céréales" }, { text: "ERP pour les métiers de la viande" }] },
      { name: "Edilogic", sector: "Location & BTP", description: "Des solutions éprouvées pour le négoce et la location d’équipements et engins du BTP.", logo: { url: "/images/logo-edilogic.png" }, image: { url: "/images/software-agorinfo.png" }, accentColor: "#f28c00", button: { label: "Visiter leur site", href: "https://www.edilogic.fr", linkType: "external", openInNewTab: true }, capabilities: [{ text: "ERP pour le négoce et la location d’équipements" }, { text: "ERP pour le négoce de matériaux" }] },
      { name: "WeNégoce", sector: "Négoce", description: "Des logiciels conçus pour piloter les activités de négoce et accélérer leur transformation.", logo: { url: "/images/logo-wenegoce.png" }, image: { url: "/images/software-wenegoce.png" }, accentColor: "#56a33a", button: { label: "Visiter leur site", href: "https://www.wenegoce.fr", linkType: "external", openInNewTab: true }, capabilities: [{ text: "ERP pour les négoces spécialisés" }, { text: "Outils de mobilité et de relation client" }] },
    ] },
    { id: 5, __component: "sections.business-characteristics", eyebrow: "VOTRE ENTREPRISE", title: "Vos caractéristiques métiers", text: "Nous cherchons à acquérir des éditeurs de logiciels verticaux avec des critères de performance et d’humain élevés.", background: "sky", button: { label: "Contactez-nous", href: "/contact", style: "secondary" }, cards: [{ title: "Savoir-faire reconnu", text: "Une expertise métier forte et un savoir-faire validé par vos clients et votre marché sectoriel.", backgroundColor: "#004b93", colSpan: 5 }, { title: "0,5 - 3M€", text: "Chiffre d’affaires annuel avec une part significative de revenu récurrent.", backgroundColor: "#dce6ff", colSpan: 3 }, { title: "Fidélité client", text: "Une forte satisfaction clients qui témoigne de leur attachement.", backgroundColor: "#ffffff", colSpan: 4 }, { title: "Équipiers engagés", text: "Des collaborateurs dévoués au service de leurs clients.", backgroundColor: "#606979", colSpan: 4 }] },
    { id: 6, __component: "sections.testimonial-metrics", testimonials: [{ quote: "Rejoindre WeSoft a été le catalyseur dont nous avions besoin. Nous avons gardé notre expertise métier tout en bénéficiant d’une force de frappe technologique mondiale.", author: "Jean-Marc Lemoine", role: "Fondateur de AgriTech Solutions", avatar: { url: "/images/testimonial-avatar.png", alternativeText: "Jean-Marc Lemoine" }, metrics: [{ value: "15+", label: "Logiciels intégrés" }, { value: "450+", label: "Collaborateurs experts" }, { value: "92%", label: "Taux de rétention clients" }, { value: "24M€", label: "Investissement R&D annuel" }] }, { quote: "WeSoft nous a permis de structurer notre croissance internationale tout en maintenant une cohésion d’équipe exceptionnelle. Un partenariat qui transforme vraiment notre quotidien.", author: "Sophie Marchand", role: "DSI de MediConnect", metrics: [{ value: "12", label: "Pays accompagnés" }, { value: "98%", label: "Satisfaction des équipes" }, { value: "3x", label: "Croissance internationale" }, { value: "24/7", label: "Support mutualisé" }] }, { quote: "Grâce à l’intégration WeSoft, nous avons réduit nos délais de mise en marché de 40 %. C’est une transformation profonde de notre manière de collaborer et d’innover.", author: "Thomas Renard", role: "CEO de FinTech Innov", metrics: [{ value: "-40%", label: "Délai de mise en marché" }, { value: "2x", label: "Capacité de déploiement" }] }], background: "blue" },
    { id: 7, __component: "sections.team", anchorId: "equipe", title: "Qui sommes-nous ?", text: "WeSoft est une structure légère qui privilégie la simplicité dictée par le pragmatisme. Cette simplicité est le reflet des profils complémentaires de ses associés.", background: "white", members: [{ name: "Jean-Marc Valet", role: "PRÉSIDENT FONDATEUR", biography: "Après avoir débuté sa carrière dans la finance, Jean-Marc accompagne depuis de nombreuses années la croissance d’éditeurs de logiciels métiers.", photo: { url: "/images/team-jean-marc.png" } }, { name: "Jérôme Martin", role: "DIRECTEUR GÉNÉRAL", biography: "Après avoir dirigé des équipes commerciales B2B spécialisées IT et financement, Jérôme a piloté pendant dix ans des éditeurs de logiciels verticaux.", photo: { url: "/images/team-jean-marc.png" } }] },
    { id: 8, __component: "sections.cta", title: "Prêt à entamer un nouveau chapitre ?", text: "Ensemble, donnons un nouveau souffle à votre solution logicielle et accélérons votre croissance sectorielle.", background: "sky", buttons: [{ label: "Prendre rendez-vous", href: "/contact", style: "primary" }, { label: "Télécharger notre brochure", href: "/brochure.pdf", style: "secondary" }] },
  ],
};

const legalBlocks = (kind: "mentions" | "privacy") => kind === "mentions" ? [
  { anchorId: "editeur", title: "1. Éditeur du Site", content: "<p><strong>Raison Sociale :</strong> WeSoft SAS</p><p><strong>Forme juridique :</strong> Société par Actions Simplifiée (SAS)</p><p><strong>Capital Social :</strong> 200 000 €</p><p><strong>Siège Social :</strong> 218 Rue de la Ronce, 76230 Isneauville, France</p><p><strong>Contact :</strong> contact@wesoft.group</p>" },
  { anchorId: "publication", title: "2. Directeur de la Publication", content: "<p>Le directeur de la publication du site WeSoft est Monsieur Jérôme Martin, en sa qualité de Président de WeSoft SAS.</p>" },
  { anchorId: "hebergement", title: "3. Hébergement du Site", content: "<p>Le site WeSoft est hébergé par Amazon Web Services (AWS). Les données sont stockées exclusivement sur des serveurs situés en Union Européenne.</p>" },
  { anchorId: "propriete", title: "4. Propriété Intellectuelle", content: "<p>L’ensemble du contenu présent sur ce site est la propriété intellectuelle exclusive de WeSoft SAS ou de ses partenaires et est protégé par les lois internationales.</p>" },
  { anchorId: "responsabilite", title: "5. Limitation de Responsabilité", content: "<p>WeSoft SAS s’efforce de fournir des informations aussi précises que possible. Le site peut contenir des liens hypertextes vers d’autres sites dont WeSoft SAS ne pourra être tenue responsable.</p>" },
] : [
  { anchorId: "introduction", title: "1. Introduction", content: "<p>WeSoft s’engage à ce que la collecte et le traitement de vos données soient conformes au règlement général sur la protection des données (RGPD) et à la loi Informatique et Libertés.</p>" },
  { anchorId: "donnees", title: "2. Données collectées", content: "<p>Nous limitons la collecte des données personnelles au strict nécessaire : informations transmises via nos formulaires et données techniques de navigation.</p>" },
  { anchorId: "finalite", title: "3. Finalité du traitement", content: "<p>Les données recueillies servent à répondre à vos demandes, assurer le suivi commercial et améliorer l’ergonomie et les services proposés.</p>" },
  { anchorId: "vos-droits", title: "4. Vos droits", content: "<p>Vous disposez notamment de droits d’accès, de rectification et de suppression concernant vos données personnelles.</p>" },
  { anchorId: "cookies", title: "5. Politique de cookies", content: "<p>Notre site utilise des cookies essentiels et, avec votre accord, des outils de mesure d’audience. Vous pouvez modifier vos préférences à tout moment.</p>" },
];

export const fallbackPages: Record<string, CmsPage> = {
  contact: { id: 2, title: "Contact", slug: "contact", blocks: [{ id: 1, __component: "sections.hero", eyebrow: "REJOIGNEZ-NOUS", title: "Entrons en contact !", text: "Vous êtes un éditeur de logiciel métier et vous souhaitez accélérer votre croissance au sein d’un écosystème d’experts ? Échangeons sur vos ambitions et l’avenir de votre solution.", image: { url: "/images/contact-office.png", alternativeText: "Bureaux WeSoft" }, background: "sky" }, { id: 2, __component: "sections.contact", title: "Formulaire de contact", officeTitle: "Le siège", officeName: "Siège Social - Isneauville", address: "218 Rue de la Ronce\n76230 Isneauville, France", socialTitle: "Suivez-nous", socialText: "Restez informé de nos actualités et des opportunités du groupe.", socialLabel: "LinkedIn - WeSoft Group", socialHref: "https://www.linkedin.com", background: "sky", fallbackForm: true }] },
  "mentions-legales": { id: 3, title: "Mentions Légales", slug: "mentions-legales", blocks: [{ id: 1, __component: "sections.hero", eyebrow: "INFORMATIONS", title: "Mentions légales", text: "Retrouvez les informations relatives à l’éditeur du site et à ses conditions d’utilisation.", background: "sky" }, { id: 2, __component: "sections.legal-content", title: "Mentions Légales", text: "Informations légales concernant l’éditeur, l’hébergeur et les conditions d’utilisation du site WeSoft.", background: "sky", sections: legalBlocks("mentions") }] },
  "politique-de-confidentialite": { id: 4, title: "Politique de Confidentialité", slug: "politique-de-confidentialite", blocks: [{ id: 1, __component: "sections.hero", eyebrow: "VOS DONNÉES", title: "Politique de confidentialité", text: "Découvrez comment WeSoft protège vos données personnelles et les droits dont vous disposez.", background: "sky" }, { id: 2, __component: "sections.legal-content", title: "Politique de Confidentialité", text: "Chez WeSoft, nous accordons une importance capitale à la protection de vos données personnelles. Cette politique détaille nos engagements en conformité avec le RGPD.", background: "sky", sections: legalBlocks("privacy") }] },
};

export function mergePageWithFallback(cms: CmsPage | null, fallback: CmsPage): CmsPage {
  if (!cms) return fallback;

  const isLegalPage = fallback.slug === "mentions-legales" || fallback.slug === "politique-de-confidentialite";
  const hasLegalContent = cms.blocks?.some((block) => block.__component === "sections.legal-content" && Array.isArray(block.sections) && block.sections.length > 0);
  if (!isLegalPage || hasLegalContent) return cms;

  const fallbackContent = fallback.blocks?.find((block) => block.__component === "sections.legal-content");
  const legacyRichText = cms.blocks?.find((block) => block.__component === "sections.rich-text");
  if (fallbackContent && legacyRichText) {
    return { ...cms, blocks: (cms.blocks || []).map((block) => block === legacyRichText ? { ...fallbackContent, id: block.id } : block) };
  }
  return fallbackContent ? { ...cms, blocks: [...(cms.blocks || []), fallbackContent] } : cms;
}
